# pythonのインデント
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'py'

# コメントアウト
[[plugins]]
repo = 'tyru/caw.vim'
on_i = 1

[[plugins]]
repo = 'kana/vim-smartchr'
hook_source = '''
  inoremap <buffer> <expr> , smartchr#loop(', ', ',')
'''


# # 補完
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_event = 'InsertCharPre'
#hook_source = '''
#  let g:deoplete#enable_at_startup = 1
#  let g:deoplete#auto_complete_delay = 0
#  let g:deoplete#auto_complete_start_length = 1
#  let g:deoplete#enable_camel_case = 0
#  let g:deoplete#enable_ignore_case = 0
#  let g:deoplete#enable_refresh_always = 0
#  let g:deoplete#enable_smart_case = 1
#  let g:deoplete#file#enable_buffer_path = 1
#  let g:deoplete#max_list = 10000
#  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
#  \ neosnippet#expandable_or_jumpable() ?
#  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
#
#'''
#on_i = 1

##vim補完
#[[plugins]]
#repo = 'Shougo/neco-vim'
#on_i = 1
#
## いろんな言語の補完
#[[plugins]]
#repo = 'Shougo/neco-syntax'
#on_i = 1
#
## python
#[[plugins]]
#repo = 'zchee/deoplete-jedi'
#on_ft = ['python', 'py']
#
## md
#[[plugins]]
#repo = 'rcmdnk/vim-markdown'
#on_ft = ['md', 'markdown']

# カッコ補完
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

