# default snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
hook_add = '''
  " Plugin key-mappings.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  " SuperTab like snippets behavior.
  " Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  "imap <expr><TAB>
  " \ pumvisible() ? "\<C-n>" :
  " \ neosnippet#expandable_or_jumpable() ?
  " \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  " For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

# complete
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
  let g:deoplete#auto_complete_start_length = 1
  let g:deoplete#enable_camel_case = 0
  let g:deoplete#enable_ignore_case = 0
  let g:deoplete#enable_refresh_always = 0
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
  \ neosnippet#expandable_or_jumpable() ?
  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

# clang include complete
[[plugins]]
repo = 'git@github.com:Shougo/neoinclude.vim.git'

# vimscript complete
[[plugins]]
repo = 'Shougo/neco-vim'
on_i = 1

# many lang complete
[[plugins]]
repo = 'Shougo/neco-syntax'
on_i = 1

# python
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python', 'py']
on_i = 1

[[plugins]]
repo = 'git@github.com:wokalski/autocomplete-flow.git'
on_ft = ['js', 'vue']


# complete clang
[[plugins]]
repo = 'git@github.com:Shougo/deoplete-clangx.git'

# [[plugins]]
# repo = 'git@github.com:tbodt/deoplete-tabnine.git'
#

[[plugins]]
repo = 'git@github.com:fszymanski/deoplete-emoji.git'

# fish script completion
[[plugins]]
repo = 'git@github.com:dag/vim-fish.git'

