# python style guide
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'py'

# auto space
[[plugins]]
repo = 'kana/vim-smartchr'
hook_add = '''
  inoremap <expr>, smartchr#loop(', ', ',')
'''
on_i = 1


# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']
on_i = 1
hook_add = '''
  set foldlevel=100
'''

# preview markdown
[[plugins]]
repo = 'git@github.com:previm/previm.git'
hook_add = '''
  augroup PrevimSettings
    autocmd!
    autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  augroup END
'''

[[plugins]]
repo = 'git@github.com:posva/vim-vue.git'
on_ft = 'vue'


# () complete
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# [[plugins]]
# repo = 'git@github.com:Floobits/floobits-neovim.git'

[[plugins]]
repo = 'git@github.com:othree/yajs.vim.git'
on_ft = 'javascript'
