# python style guide
[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'py'

# auto space
[[plugins]]
repo = 'kana/vim-smartchr'
hook_add = '''
  inoremap <expr>, smartchr#loop(', ', ',')
'''
on_i = 1


# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']
on_i = 1
hook_add = '''
  set foldlevel=100
'''

# preview markdown
[[plugins]]
repo = 'git@github.com:previm/previm.git'
hook_add = '''
  autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
'''

[[plugins]]
repo = 'git@github.com:posva/vim-vue.git'
on_ft = 'vue'
on_i = 1


# () complete
# [[plugins]]
# repo = 'cohama/lexima.vim'
# on_i = 1
# hook_add = '''
#   let g:lexima_enable_basic_rules = 0
# '''

# group programming
# [[plugins]]
# repo = 'git@github.com:Floobits/floobits-neovim.git'

[[plugins]]
repo = 'git@github.com:othree/yajs.vim.git'
on_ft = 'javascript'
on_i = 1

# c, cpp connect header and sources.
[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'git@github.com:aklt/plantuml-syntax.git'
on_ft = ['uml']

# toml highlight
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# presen
[[plugins]]
repo = 'git@github.com:thinca/vim-showtime.git'
hook_add = '''
  function! s:MyShowtimeStart() abort
    ShowtimeStart
    IndentLinesDisable
  endfunction

  command! InazumaShowtimeStart call s:MyShowtimeStart()
'''
on_ft = 'md'

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_i = 1

# syntax highlight json
[[plugins]]
repo =  'elzr/vim-json'
hook_add = '''
  let g:vim_json_syntax_conceal = 0
'''
on_ft = 'json'


[[plugins]]
repo = 'vim-scripts/fcitx.vim'
on_i = 1

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_ft = ['md', 'markdown']
hook_add = '''
  " let g:gfm_syntax_emoji_conceal=1
'''

[[plugins]]
repo = 'https://github.com/tweekmonster/helpful.vim'
on_ft = ['md', 'markdown', 'help']

